-- Round 3: the seeded catalogue — the tiles you tap instead of typing.
--
-- GENERATED FILE. Do not edit by hand: change src/lib/catalogue-seed.ts and run
-- `npm run seed:sql`. 569 items across 10 categories.
--
-- These rows have household_id null, meaning they are shared by every
-- household and belong to none. The insert policy in 0002 deliberately forbids
-- creating rows like that from the app, so this has to be run here, in the SQL
-- editor, where policies don't apply.
--
-- Safe to re-run: on conflict it updates the category, icon, order and
-- suggested rank, so re-running after changing the catalogue applies the new
-- values rather than erroring or duplicating. Re-running this is also how the
-- old emoji icons get swapped for line-drawing slugs.
--
-- Requires 0004 and 0005 to have run first (they add the suggested_rank and
-- emoji columns).

insert into public.catalogue_items (name, category, icon, emoji, sort_order, suggested_rank)
values
  ('apples', 'Fruit & vegetables', 'apple', '🍎', 0, 14),
  ('bananas', 'Fruit & vegetables', 'banana', '🍌', 1, 4),
  ('oranges', 'Fruit & vegetables', 'citrus', '🍊', 2, null),
  ('lemons', 'Fruit & vegetables', 'citrus', '🍋', 3, null),
  ('limes', 'Fruit & vegetables', 'citrus', null, 4, null),
  ('strawberries', 'Fruit & vegetables', 'strawberry', '🍓', 5, null),
  ('raspberries', 'Fruit & vegetables', 'strawberry', null, 6, null),
  ('blueberries', 'Fruit & vegetables', 'strawberry', '🫐', 7, null),
  ('grapes', 'Fruit & vegetables', 'grapes', '🍇', 8, null),
  ('cherries', 'Fruit & vegetables', 'strawberry', '🍒', 9, null),
  ('melon', 'Fruit & vegetables', 'melon', '🍈', 10, null),
  ('watermelon', 'Fruit & vegetables', 'melon', '🍉', 11, null),
  ('peaches', 'Fruit & vegetables', 'apple', '🍑', 12, null),
  ('pears', 'Fruit & vegetables', 'apple', '🍐', 13, null),
  ('plums', 'Fruit & vegetables', 'apple', null, 14, null),
  ('apricots', 'Fruit & vegetables', 'apple', null, 15, null),
  ('figs', 'Fruit & vegetables', 'apple', null, 16, null),
  ('pineapple', 'Fruit & vegetables', 'melon', '🍍', 17, null),
  ('kiwi', 'Fruit & vegetables', 'melon', '🥝', 18, null),
  ('mango', 'Fruit & vegetables', 'melon', '🥭', 19, null),
  ('pomegranate', 'Fruit & vegetables', 'apple', null, 20, null),
  ('avocado', 'Fruit & vegetables', 'melon', '🥑', 21, null),
  ('tomatoes', 'Fruit & vegetables', 'tomato', '🍅', 22, 5),
  ('cherry tomatoes', 'Fruit & vegetables', 'tomato', '🍅', 23, null),
  ('potatoes', 'Fruit & vegetables', 'potato', '🥔', 24, 7),
  ('sweet potato', 'Fruit & vegetables', 'potato', '🍠', 25, null),
  ('onions', 'Fruit & vegetables', 'onion', '🧅', 26, 6),
  ('spring onions', 'Fruit & vegetables', 'onion', null, 27, null),
  ('garlic', 'Fruit & vegetables', 'garlic', '🧄', 28, null),
  ('carrots', 'Fruit & vegetables', 'carrot', '🥕', 29, 20),
  ('peppers', 'Fruit & vegetables', 'pepper', '🫑', 30, null),
  ('chillies', 'Fruit & vegetables', 'pepper', '🌶️', 31, null),
  ('courgette', 'Fruit & vegetables', 'cucumber', '🥒', 32, null),
  ('aubergine', 'Fruit & vegetables', 'cucumber', '🍆', 33, null),
  ('cucumber', 'Fruit & vegetables', 'cucumber', '🥒', 34, null),
  ('lettuce', 'Fruit & vegetables', 'lettuce', '🥬', 35, 19),
  ('rocket', 'Fruit & vegetables', 'lettuce', null, 36, null),
  ('spinach', 'Fruit & vegetables', 'lettuce', '🥬', 37, null),
  ('broccoli', 'Fruit & vegetables', 'broccoli', '🥦', 38, null),
  ('cauliflower', 'Fruit & vegetables', 'broccoli', null, 39, null),
  ('cabbage', 'Fruit & vegetables', 'broccoli', null, 40, null),
  ('brussels sprouts', 'Fruit & vegetables', 'broccoli', null, 41, null),
  ('asparagus', 'Fruit & vegetables', 'lettuce', null, 42, null),
  ('artichoke', 'Fruit & vegetables', 'broccoli', null, 43, null),
  ('fennel', 'Fruit & vegetables', 'broccoli', null, 44, null),
  ('mushrooms', 'Fruit & vegetables', 'mushroom', '🍄', 45, null),
  ('sweetcorn', 'Fruit & vegetables', 'corn', '🌽', 46, null),
  ('green beans', 'Fruit & vegetables', 'peas', null, 47, null),
  ('peas', 'Fruit & vegetables', 'peas', null, 48, null),
  ('leek', 'Fruit & vegetables', 'onion', null, 49, null),
  ('celery', 'Fruit & vegetables', 'lettuce', null, 50, null),
  ('radish', 'Fruit & vegetables', 'cucumber', null, 51, null),
  ('beetroot', 'Fruit & vegetables', 'cucumber', null, 52, null),
  ('pumpkin', 'Fruit & vegetables', 'cucumber', '🎃', 53, null),
  ('ginger', 'Fruit & vegetables', 'cucumber', null, 54, null),
  ('parsley', 'Fruit & vegetables', 'herbs', '🌿', 55, null),
  ('basil', 'Fruit & vegetables', 'herbs', '🌿', 56, null),
  ('coriander', 'Fruit & vegetables', 'herbs', '🌿', 57, null),
  ('mint', 'Fruit & vegetables', 'herbs', '🌿', 58, null),
  ('rosemary', 'Fruit & vegetables', 'herbs', '🌿', 59, null),
  ('salad bag', 'Fruit & vegetables', 'lettuce', null, 60, null),
  ('nectarines', 'Fruit & vegetables', 'apple', null, 61, null),
  ('clementines', 'Fruit & vegetables', 'citrus', null, 62, null),
  ('grapefruit', 'Fruit & vegetables', 'citrus', null, 63, null),
  ('blackberries', 'Fruit & vegetables', 'strawberry', null, 64, null),
  ('lingonberries', 'Fruit & vegetables', 'strawberry', null, 65, null),
  ('cranberries', 'Fruit & vegetables', 'strawberry', null, 66, null),
  ('rhubarb', 'Fruit & vegetables', 'herbs', null, 67, null),
  ('passion fruit', 'Fruit & vegetables', 'melon', null, 68, null),
  ('coconut', 'Fruit & vegetables', 'melon', null, 69, null),
  ('papaya', 'Fruit & vegetables', 'melon', null, 70, null),
  ('shallots', 'Fruit & vegetables', 'onion', null, 71, null),
  ('calçots', 'Fruit & vegetables', 'onion', null, 72, null),
  ('swede', 'Fruit & vegetables', 'potato', null, 73, null),
  ('turnip', 'Fruit & vegetables', 'potato', null, 74, null),
  ('parsnip', 'Fruit & vegetables', 'carrot', null, 75, null),
  ('celeriac', 'Fruit & vegetables', 'potato', null, 76, null),
  ('new potatoes', 'Fruit & vegetables', 'potato', '🥔', 77, null),
  ('butternut squash', 'Fruit & vegetables', 'melon', '🎃', 78, null),
  ('kale', 'Fruit & vegetables', 'lettuce', '🥬', 79, null),
  ('chard', 'Fruit & vegetables', 'lettuce', null, 80, null),
  ('pak choi', 'Fruit & vegetables', 'lettuce', null, 81, null),
  ('endive', 'Fruit & vegetables', 'lettuce', null, 82, null),
  ('escarole', 'Fruit & vegetables', 'lettuce', null, 83, null),
  ('watercress', 'Fruit & vegetables', 'herbs', null, 84, null),
  ('sugar snap peas', 'Fruit & vegetables', 'peas', null, 85, null),
  ('edamame', 'Fruit & vegetables', 'peas', null, 86, null),
  ('beansprouts', 'Fruit & vegetables', 'herbs', null, 87, null),
  ('corn on the cob', 'Fruit & vegetables', 'corn', '🌽', 88, null),
  ('dill', 'Fruit & vegetables', 'herbs', '🌿', 89, null),
  ('chives', 'Fruit & vegetables', 'herbs', '🌿', 90, null),
  ('sage', 'Fruit & vegetables', 'herbs', '🌿', 91, null),
  ('tarragon', 'Fruit & vegetables', 'herbs', '🌿', 92, null),
  ('bread', 'Bakery', 'bread', '🍞', 1000, 2),
  ('baguette', 'Bakery', 'baguette', '🥖', 1001, null),
  ('sliced bread', 'Bakery', 'bread', null, 1002, null),
  ('wholemeal bread', 'Bakery', 'bread', null, 1003, null),
  ('sourdough', 'Bakery', 'bread', null, 1004, null),
  ('bread rolls', 'Bakery', 'bread', null, 1005, null),
  ('ciabatta', 'Bakery', 'bread', null, 1006, null),
  ('focaccia', 'Bakery', 'bread', null, 1007, null),
  ('brioche', 'Bakery', 'bread', null, 1008, null),
  ('croissants', 'Bakery', 'croissant', '🥐', 1009, null),
  ('bagels', 'Bakery', 'cake', '🥯', 1010, null),
  ('pitta bread', 'Bakery', 'bread', null, 1011, null),
  ('naan', 'Bakery', 'bread', null, 1012, null),
  ('tortillas', 'Bakery', 'bread', '🌯', 1013, null),
  ('pastries', 'Bakery', 'croissant', '🥧', 1014, null),
  ('cake', 'Bakery', 'cake', '🍰', 1015, null),
  ('muffins', 'Bakery', 'cake', '🧁', 1016, null),
  ('doughnuts', 'Bakery', 'croissant', '🍩', 1017, null),
  ('scones', 'Bakery', 'bread', null, 1018, null),
  ('biscuits', 'Bakery', 'cookie', '🍪', 1019, null),
  ('crispbread', 'Bakery', 'bread', null, 1020, null),
  ('rye bread', 'Bakery', 'bread', null, 1021, null),
  ('seeded bread', 'Bakery', 'bread', null, 1022, null),
  ('gluten-free bread', 'Bakery', 'bread', null, 1023, null),
  ('hot dog buns', 'Bakery', 'bread', '🌭', 1024, null),
  ('burger buns', 'Bakery', 'bread', null, 1025, null),
  ('cinnamon buns', 'Bakery', 'croissant', null, 1026, null),
  ('sponge cake', 'Bakery', 'cake', null, 1027, null),
  ('tart', 'Bakery', 'cake', '🥧', 1028, null),
  ('croutons', 'Bakery', 'bread', null, 1029, null),
  ('milk', 'Dairy & eggs', 'milk', '🥛', 2000, 1),
  ('semi-skimmed milk', 'Dairy & eggs', 'milk', null, 2001, null),
  ('oat milk', 'Dairy & eggs', 'milk', null, 2002, null),
  ('almond milk', 'Dairy & eggs', 'milk', null, 2003, null),
  ('soy milk', 'Dairy & eggs', 'milk', null, 2004, null),
  ('eggs', 'Dairy & eggs', 'egg', '🥚', 2005, 3),
  ('butter', 'Dairy & eggs', 'butter', '🧈', 2006, 12),
  ('margarine', 'Dairy & eggs', 'butter', null, 2007, null),
  ('cheese', 'Dairy & eggs', 'cheese', '🧀', 2008, 11),
  ('cheddar', 'Dairy & eggs', 'cheese', '🧀', 2009, null),
  ('grated cheese', 'Dairy & eggs', 'cheese', null, 2010, null),
  ('goat cheese', 'Dairy & eggs', 'cheese', null, 2011, null),
  ('blue cheese', 'Dairy & eggs', 'cheese', null, 2012, null),
  ('brie', 'Dairy & eggs', 'cheese', null, 2013, null),
  ('manchego', 'Dairy & eggs', 'cheese', null, 2014, null),
  ('mozzarella', 'Dairy & eggs', 'cheese', null, 2015, null),
  ('parmesan', 'Dairy & eggs', 'cheese', null, 2016, null),
  ('feta', 'Dairy & eggs', 'cheese', null, 2017, null),
  ('ricotta', 'Dairy & eggs', 'cheese', null, 2018, null),
  ('mascarpone', 'Dairy & eggs', 'cheese', null, 2019, null),
  ('cream cheese', 'Dairy & eggs', 'cheese', null, 2020, null),
  ('cottage cheese', 'Dairy & eggs', 'cheese', null, 2021, null),
  ('yoghurt', 'Dairy & eggs', 'yoghurt', null, 2022, 13),
  ('greek yoghurt', 'Dairy & eggs', 'yoghurt', null, 2023, null),
  ('kefir', 'Dairy & eggs', 'yoghurt', null, 2024, null),
  ('cream', 'Dairy & eggs', 'yoghurt', null, 2025, null),
  ('sour cream', 'Dairy & eggs', 'yoghurt', null, 2026, null),
  ('creme fraiche', 'Dairy & eggs', 'yoghurt', null, 2027, null),
  ('custard', 'Dairy & eggs', 'yoghurt', null, 2028, null),
  ('condensed milk', 'Dairy & eggs', 'milk', null, 2029, null),
  ('halloumi', 'Dairy & eggs', 'cheese', '🧀', 2030, null),
  ('gouda', 'Dairy & eggs', 'cheese', '🧀', 2031, null),
  ('emmental', 'Dairy & eggs', 'cheese', '🧀', 2032, null),
  ('camembert', 'Dairy & eggs', 'cheese', '🧀', 2033, null),
  ('mató', 'Dairy & eggs', 'cheese', null, 2034, null),
  ('quark', 'Dairy & eggs', 'yoghurt', null, 2035, null),
  ('skyr', 'Dairy & eggs', 'yoghurt', null, 2036, null),
  ('filmjölk', 'Dairy & eggs', 'milk', null, 2037, null),
  ('buttermilk', 'Dairy & eggs', 'milk', '🥛', 2038, null),
  ('lactose-free milk', 'Dairy & eggs', 'milk', '🥛', 2039, null),
  ('whipping cream', 'Dairy & eggs', 'milk', null, 2040, null),
  ('egg whites', 'Dairy & eggs', 'egg', '🥚', 2041, null),
  ('chicken breast', 'Meat & fish', 'chicken', '🍗', 3000, 8),
  ('chicken thighs', 'Meat & fish', 'chicken', '🍗', 3001, null),
  ('chicken wings', 'Meat & fish', 'chicken', '🍗', 3002, null),
  ('whole chicken', 'Meat & fish', 'chicken', '🍗', 3003, null),
  ('turkey', 'Meat & fish', 'chicken', null, 3004, null),
  ('minced beef', 'Meat & fish', 'meat', null, 3005, null),
  ('beef steak', 'Meat & fish', 'meat', '🥩', 3006, null),
  ('beef stewing', 'Meat & fish', 'meat', null, 3007, null),
  ('burger patties', 'Meat & fish', 'meat', '🍔', 3008, null),
  ('meatballs', 'Meat & fish', 'meat', null, 3009, null),
  ('pork chops', 'Meat & fish', 'meat', '🥩', 3010, null),
  ('pork belly', 'Meat & fish', 'meat', null, 3011, null),
  ('ribs', 'Meat & fish', 'meat', null, 3012, null),
  ('lamb', 'Meat & fish', 'meat', null, 3013, null),
  ('veal', 'Meat & fish', 'meat', null, 3014, null),
  ('duck', 'Meat & fish', 'chicken', null, 3015, null),
  ('rabbit', 'Meat & fish', 'meat', null, 3016, null),
  ('sausages', 'Meat & fish', 'sausage', '🌭', 3017, null),
  ('bacon', 'Meat & fish', 'sausage', '🥓', 3018, null),
  ('ham', 'Meat & fish', 'sausage', null, 3019, null),
  ('chorizo', 'Meat & fish', 'sausage', null, 3020, null),
  ('salami', 'Meat & fish', 'sausage', null, 3021, null),
  ('pate', 'Meat & fish', 'sausage', null, 3022, null),
  ('black pudding', 'Meat & fish', 'sausage', null, 3023, null),
  ('salmon', 'Meat & fish', 'fish', '🐟', 3024, null),
  ('smoked salmon', 'Meat & fish', 'fish', '🐟', 3025, null),
  ('white fish', 'Meat & fish', 'fish', '🐟', 3026, null),
  ('cod', 'Meat & fish', 'fish', null, 3027, null),
  ('hake', 'Meat & fish', 'fish', null, 3028, null),
  ('sea bass', 'Meat & fish', 'fish', null, 3029, null),
  ('tuna steak', 'Meat & fish', 'meat', '🐟', 3030, null),
  ('sardines', 'Meat & fish', 'fish', '🐟', 3031, null),
  ('anchovies', 'Meat & fish', 'fish', null, 3032, null),
  ('prawns', 'Meat & fish', 'shrimp', '🦐', 3033, null),
  ('mussels', 'Meat & fish', 'shrimp', '🦪', 3034, null),
  ('clams', 'Meat & fish', 'shrimp', null, 3035, null),
  ('squid', 'Meat & fish', 'shrimp', '🦑', 3036, null),
  ('octopus', 'Meat & fish', 'shrimp', '🐙', 3037, null),
  ('crab', 'Meat & fish', 'shrimp', '🦀', 3038, null),
  ('pork mince', 'Meat & fish', 'meat', '🥩', 3039, null),
  ('chicken mince', 'Meat & fish', 'chicken', null, 3040, null),
  ('turkey mince', 'Meat & fish', 'meat', null, 3041, null),
  ('lardons', 'Meat & fish', 'sausage', '🥓', 3042, null),
  ('cured ham', 'Meat & fish', 'meat', null, 3043, null),
  ('fuet', 'Meat & fish', 'sausage', null, 3044, null),
  ('butifarra', 'Meat & fish', 'sausage', null, 3045, null),
  ('falukorv', 'Meat & fish', 'sausage', null, 3046, null),
  ('pancetta', 'Meat & fish', 'sausage', '🥓', 3047, null),
  ('prosciutto', 'Meat & fish', 'meat', null, 3048, null),
  ('mortadella', 'Meat & fish', 'sausage', null, 3049, null),
  ('liver', 'Meat & fish', 'meat', null, 3050, null),
  ('pork loin', 'Meat & fish', 'meat', '🥩', 3051, null),
  ('herring', 'Meat & fish', 'fish', '🐟', 3052, null),
  ('pickled herring', 'Meat & fish', 'jar', null, 3053, null),
  ('mackerel', 'Meat & fish', 'fish', '🐟', 3054, null),
  ('trout', 'Meat & fish', 'fish', '🐟', 3055, null),
  ('haddock', 'Meat & fish', 'fish', '🐟', 3056, null),
  ('monkfish', 'Meat & fish', 'fish', '🐟', 3057, null),
  ('scallops', 'Meat & fish', 'shrimp', '🦪', 3058, null),
  ('lobster', 'Meat & fish', 'shrimp', '🦀', 3059, null),
  ('fish roe', 'Meat & fish', 'jar', null, 3060, null),
  ('pasta', 'Pantry', 'pasta', '🍝', 4000, 9),
  ('spaghetti', 'Pantry', 'pasta', '🍝', 4001, null),
  ('lasagne sheets', 'Pantry', 'pasta', null, 4002, null),
  ('gnocchi', 'Pantry', 'pasta', null, 4003, null),
  ('rice', 'Pantry', 'rice', '🍚', 4004, 10),
  ('risotto rice', 'Pantry', 'rice', null, 4005, null),
  ('noodles', 'Pantry', 'pasta', '🍜', 4006, null),
  ('rice noodles', 'Pantry', 'pasta', null, 4007, null),
  ('couscous', 'Pantry', 'pasta', null, 4008, null),
  ('quinoa', 'Pantry', 'rice', null, 4009, null),
  ('polenta', 'Pantry', 'rice', null, 4010, null),
  ('bulgur', 'Pantry', 'rice', null, 4011, null),
  ('lentils', 'Pantry', 'can', null, 4012, null),
  ('chickpeas', 'Pantry', 'can', null, 4013, null),
  ('kidney beans', 'Pantry', 'can', null, 4014, null),
  ('white beans', 'Pantry', 'can', null, 4015, null),
  ('tinned tomatoes', 'Pantry', 'tomato', '🥫', 4016, 21),
  ('passata', 'Pantry', 'can', null, 4017, null),
  ('tomato sauce', 'Pantry', 'sauce', '🥫', 4018, null),
  ('tomato puree', 'Pantry', 'tube', null, 4019, null),
  ('tinned tuna', 'Pantry', 'fish', '🥫', 4020, null),
  ('tinned sweetcorn', 'Pantry', 'can', '🥫', 4021, null),
  ('coconut milk', 'Pantry', 'milk', null, 4022, null),
  ('olive oil', 'Pantry', 'oil', '🫒', 4023, 15),
  ('sunflower oil', 'Pantry', 'oil', null, 4024, null),
  ('sesame oil', 'Pantry', 'oil', null, 4025, null),
  ('vinegar', 'Pantry', 'oil', null, 4026, null),
  ('balsamic vinegar', 'Pantry', 'oil', null, 4027, null),
  ('salt', 'Pantry', 'salt', '🧂', 4028, null),
  ('pepper', 'Pantry', 'salt', null, 4029, null),
  ('sugar', 'Pantry', 'salt', null, 4030, null),
  ('brown sugar', 'Pantry', 'salt', null, 4031, null),
  ('icing sugar', 'Pantry', 'salt', null, 4032, null),
  ('flour', 'Pantry', 'salt', null, 4033, null),
  ('cornflour', 'Pantry', 'corn', null, 4034, null),
  ('baking powder', 'Pantry', 'salt', null, 4035, null),
  ('yeast', 'Pantry', 'salt', null, 4036, null),
  ('vanilla', 'Pantry', 'spice', null, 4037, null),
  ('cocoa powder', 'Pantry', 'spice', null, 4038, null),
  ('chocolate chips', 'Pantry', 'juice', null, 4039, null),
  ('honey', 'Pantry', 'honey', '🍯', 4040, null),
  ('jam', 'Pantry', 'honey', null, 4041, null),
  ('marmalade', 'Pantry', 'honey', null, 4042, null),
  ('peanut butter', 'Pantry', 'honey', '🥜', 4043, null),
  ('chocolate spread', 'Pantry', 'honey', null, 4044, null),
  ('tahini', 'Pantry', 'honey', null, 4045, null),
  ('cereal', 'Pantry', 'cereal', '🥣', 4046, null),
  ('porridge oats', 'Pantry', 'cereal', '🥣', 4047, null),
  ('muesli', 'Pantry', 'cereal', null, 4048, null),
  ('granola', 'Pantry', 'cereal', null, 4049, null),
  ('stock cubes', 'Pantry', 'sauce', null, 4050, null),
  ('soy sauce', 'Pantry', 'sauce', null, 4051, null),
  ('fish sauce', 'Pantry', 'fish', null, 4052, null),
  ('worcestershire sauce', 'Pantry', 'sauce', null, 4053, null),
  ('hot sauce', 'Pantry', 'sauce', null, 4054, null),
  ('bbq sauce', 'Pantry', 'sauce', null, 4055, null),
  ('mustard', 'Pantry', 'sauce', null, 4056, null),
  ('mayonnaise', 'Pantry', 'sauce', null, 4057, null),
  ('ketchup', 'Pantry', 'sauce', null, 4058, null),
  ('pesto', 'Pantry', 'jar', null, 4059, null),
  ('curry paste', 'Pantry', 'sauce', null, 4060, null),
  ('harissa', 'Pantry', 'sauce', null, 4061, null),
  ('olives', 'Pantry', 'jar', '🫒', 4062, null),
  ('pickles', 'Pantry', 'jar', null, 4063, null),
  ('capers', 'Pantry', 'jar', null, 4064, null),
  ('nuts', 'Pantry', 'nuts', '🥜', 4065, null),
  ('almonds', 'Pantry', 'nuts', null, 4066, null),
  ('walnuts', 'Pantry', 'nuts', null, 4067, null),
  ('cashews', 'Pantry', 'nuts', null, 4068, null),
  ('pistachios', 'Pantry', 'nuts', null, 4069, null),
  ('raisins', 'Pantry', 'grapes', null, 4070, null),
  ('dates', 'Pantry', 'nuts', null, 4071, null),
  ('dried apricots', 'Pantry', 'seeds', null, 4072, null),
  ('chia seeds', 'Pantry', 'nuts', null, 4073, null),
  ('sunflower seeds', 'Pantry', 'nuts', null, 4074, null),
  ('pumpkin seeds', 'Pantry', 'cucumber', null, 4075, null),
  ('spices', 'Pantry', 'spice', null, 4076, null),
  ('paprika', 'Pantry', 'spice', null, 4077, null),
  ('oregano', 'Pantry', 'herbs', null, 4078, null),
  ('thyme', 'Pantry', 'herbs', null, 4079, null),
  ('bay leaves', 'Pantry', 'herbs', null, 4080, null),
  ('cinnamon', 'Pantry', 'spice', null, 4081, null),
  ('nutmeg', 'Pantry', 'spice', null, 4082, null),
  ('cumin', 'Pantry', 'spice', null, 4083, null),
  ('turmeric', 'Pantry', 'spice', null, 4084, null),
  ('curry powder', 'Pantry', 'spice', null, 4085, null),
  ('chilli flakes', 'Pantry', 'spice', null, 4086, null),
  ('garlic powder', 'Pantry', 'spice', null, 4087, null),
  ('breadcrumbs', 'Pantry', 'salt', null, 4088, null),
  ('macaroni', 'Pantry', 'pasta', null, 4089, null),
  ('penne', 'Pantry', 'pasta', null, 4090, null),
  ('fusilli', 'Pantry', 'pasta', null, 4091, null),
  ('tagliatelle', 'Pantry', 'pasta', '🍝', 4092, null),
  ('ravioli', 'Pantry', 'pasta', null, 4093, null),
  ('tortellini', 'Pantry', 'pasta', null, 4094, null),
  ('orzo', 'Pantry', 'pasta', null, 4095, null),
  ('egg noodles', 'Pantry', 'pasta', '🍜', 4096, null),
  ('ramen', 'Pantry', 'pasta', '🍜', 4097, null),
  ('paella rice', 'Pantry', 'rice', '🍚', 4098, null),
  ('brown rice', 'Pantry', 'rice', '🍚', 4099, null),
  ('sushi rice', 'Pantry', 'rice', '🍚', 4100, null),
  ('rye flour', 'Pantry', 'flourBag', null, 4101, null),
  ('semolina', 'Pantry', 'flourBag', null, 4102, null),
  ('chickpea flour', 'Pantry', 'flourBag', null, 4103, null),
  ('bicarbonate of soda', 'Pantry', 'spice', null, 4104, null),
  ('gelatine', 'Pantry', 'spice', null, 4105, null),
  ('baked beans', 'Pantry', 'can', '🥫', 4106, null),
  ('butter beans', 'Pantry', 'can', '🥫', 4107, null),
  ('black beans', 'Pantry', 'can', '🥫', 4108, null),
  ('broad beans', 'Pantry', 'can', '🥫', 4109, null),
  ('tinned sardines', 'Pantry', 'can', '🥫', 4110, null),
  ('tinned mackerel', 'Pantry', 'can', '🥫', 4111, null),
  ('evaporated milk', 'Pantry', 'can', '🥫', 4112, null),
  ('sun-dried tomatoes', 'Pantry', 'jar', null, 4113, null),
  ('piquillo peppers', 'Pantry', 'jar', null, 4114, null),
  ('gherkins', 'Pantry', 'jar', null, 4115, null),
  ('sauerkraut', 'Pantry', 'jar', null, 4116, null),
  ('kimchi', 'Pantry', 'jar', null, 4117, null),
  ('miso', 'Pantry', 'jar', null, 4118, null),
  ('oyster sauce', 'Pantry', 'sauce', null, 4119, null),
  ('sriracha', 'Pantry', 'sauce', '🌶️', 4120, null),
  ('tabasco', 'Pantry', 'sauce', '🌶️', 4121, null),
  ('aioli', 'Pantry', 'sauce', null, 4122, null),
  ('romesco', 'Pantry', 'sauce', null, 4123, null),
  ('sofregit', 'Pantry', 'jar', null, 4124, null),
  ('saffron', 'Pantry', 'spice', null, 4125, null),
  ('pimentón', 'Pantry', 'spice', null, 4126, null),
  ('italian herbs', 'Pantry', 'herbs', '🌿', 4127, null),
  ('fennel seeds', 'Pantry', 'seeds', null, 4128, null),
  ('sesame seeds', 'Pantry', 'seeds', null, 4129, null),
  ('flaxseed', 'Pantry', 'seeds', null, 4130, null),
  ('hazelnuts', 'Pantry', 'nuts', '🥜', 4131, null),
  ('peanuts', 'Pantry', 'nuts', '🥜', 4132, null),
  ('pine nuts', 'Pantry', 'nuts', null, 4133, null),
  ('prunes', 'Pantry', 'bag', null, 4134, null),
  ('dried cranberries', 'Pantry', 'bag', null, 4135, null),
  ('coconut flakes', 'Pantry', 'bag', null, 4136, null),
  ('maple syrup', 'Pantry', 'honey', null, 4137, null),
  ('lingonberry jam', 'Pantry', 'jar', null, 4138, null),
  ('panko', 'Pantry', 'bag', null, 4139, null),
  ('stuffing', 'Pantry', 'bag', null, 4140, null),
  ('frozen peas', 'Frozen', 'frozen', null, 5000, null),
  ('frozen spinach', 'Frozen', 'lettuce', null, 5001, null),
  ('frozen vegetables', 'Frozen', 'frozen', null, 5002, null),
  ('frozen berries', 'Frozen', 'frozen', null, 5003, null),
  ('frozen chips', 'Frozen', 'frozen', '🍟', 5004, null),
  ('frozen pizza', 'Frozen', 'frozen', '🍕', 5005, null),
  ('frozen fish', 'Frozen', 'fish', null, 5006, null),
  ('frozen prawns', 'Frozen', 'shrimp', null, 5007, null),
  ('frozen burgers', 'Frozen', 'frozen', null, 5008, null),
  ('chicken nuggets', 'Frozen', 'chicken', null, 5009, null),
  ('frozen pastry', 'Frozen', 'frozen', null, 5010, null),
  ('frozen bread', 'Frozen', 'frozen', null, 5011, null),
  ('ice cream', 'Frozen', 'iceCream', '🍨', 5012, null),
  ('sorbet', 'Frozen', 'iceCream', null, 5013, null),
  ('ice cubes', 'Frozen', 'iceCream', '🧊', 5014, null),
  ('frozen broccoli', 'Frozen', 'frozen', '🥦', 5015, null),
  ('frozen sweetcorn', 'Frozen', 'frozen', '🌽', 5016, null),
  ('fish fingers', 'Frozen', 'frozen', null, 5017, null),
  ('ready meals', 'Frozen', 'frozen', null, 5018, null),
  ('frozen lasagne', 'Frozen', 'frozen', null, 5019, null),
  ('frozen falafel', 'Frozen', 'frozen', null, 5020, null),
  ('spring rolls', 'Frozen', 'frozen', null, 5021, null),
  ('ice lollies', 'Frozen', 'lolly', null, 5022, null),
  ('frozen waffles', 'Frozen', 'frozen', null, 5023, null),
  ('pizza base', 'Frozen', 'frozen', '🍕', 5024, null),
  ('frozen herbs', 'Frozen', 'frozen', '🌿', 5025, null),
  ('water', 'Drinks', 'water', '💧', 6000, 22),
  ('sparkling water', 'Drinks', 'water', null, 6001, null),
  ('coconut water', 'Drinks', 'water', null, 6002, null),
  ('orange juice', 'Drinks', 'juice', '🧃', 6003, null),
  ('apple juice', 'Drinks', 'juice', '🧃', 6004, null),
  ('lemonade', 'Drinks', 'juice', null, 6005, null),
  ('cola', 'Drinks', 'juice', null, 6006, null),
  ('soft drinks', 'Drinks', 'juice', '🥤', 6007, null),
  ('tonic water', 'Drinks', 'juice', null, 6008, null),
  ('iced tea', 'Drinks', 'tea', null, 6009, null),
  ('energy drink', 'Drinks', 'juice', null, 6010, null),
  ('kombucha', 'Drinks', 'beer', null, 6011, null),
  ('coffee', 'Drinks', 'coffee', '☕', 6012, 16),
  ('ground coffee', 'Drinks', 'coffee', '☕', 6013, null),
  ('coffee capsules', 'Drinks', 'coffee', '☕', 6014, null),
  ('tea', 'Drinks', 'tea', '🍵', 6015, null),
  ('herbal tea', 'Drinks', 'tea', '🍵', 6016, null),
  ('hot chocolate', 'Drinks', 'coffee', null, 6017, null),
  ('red wine', 'Drinks', 'wine', '🍷', 6018, null),
  ('white wine', 'Drinks', 'wine', '🍷', 6019, null),
  ('rose wine', 'Drinks', 'wine', '🍷', 6020, null),
  ('cava', 'Drinks', 'wine', '🍾', 6021, null),
  ('beer', 'Drinks', 'beer', '🍺', 6022, null),
  ('cider', 'Drinks', 'beer', null, 6023, null),
  ('vermouth', 'Drinks', 'wine', null, 6024, null),
  ('gin', 'Drinks', 'wine', null, 6025, null),
  ('whisky', 'Drinks', 'wine', '🥃', 6026, null),
  ('rum', 'Drinks', 'wine', null, 6027, null),
  ('vodka', 'Drinks', 'wine', null, 6028, null),
  ('mineral water', 'Drinks', 'water', '💧', 6029, null),
  ('cordial', 'Drinks', 'juice', null, 6030, null),
  ('tomato juice', 'Drinks', 'juice', '🍅', 6031, null),
  ('pineapple juice', 'Drinks', 'juice', '🍍', 6032, null),
  ('smoothie', 'Drinks', 'juice', '🥤', 6033, null),
  ('sports drink', 'Drinks', 'water', null, 6034, null),
  ('alcohol-free beer', 'Drinks', 'beer', '🍺', 6035, null),
  ('lager', 'Drinks', 'beer', '🍺', 6036, null),
  ('ale', 'Drinks', 'beer', '🍺', 6037, null),
  ('stout', 'Drinks', 'beer', '🍺', 6038, null),
  ('prosecco', 'Drinks', 'wine', null, 6039, null),
  ('champagne', 'Drinks', 'wine', null, 6040, null),
  ('sherry', 'Drinks', 'wine', null, 6041, null),
  ('port', 'Drinks', 'wine', null, 6042, null),
  ('aquavit', 'Drinks', 'wine', '🥃', 6043, null),
  ('glögg', 'Drinks', 'wine', null, 6044, null),
  ('decaf coffee', 'Drinks', 'coffee', '☕', 6045, null),
  ('instant coffee', 'Drinks', 'coffee', '☕', 6046, null),
  ('coffee beans', 'Drinks', 'coffee', '☕', 6047, null),
  ('green tea', 'Drinks', 'tea', '🍵', 6048, null),
  ('chai', 'Drinks', 'tea', '🍵', 6049, null),
  ('rooibos', 'Drinks', 'tea', '🍵', 6050, null),
  ('crisps', 'Snacks', 'crisps', null, 7000, null),
  ('tortilla chips', 'Snacks', 'crisps', null, 7001, null),
  ('nachos', 'Snacks', 'crisps', null, 7002, null),
  ('pretzels', 'Snacks', 'crisps', '🥨', 7003, null),
  ('popcorn', 'Snacks', 'crisps', '🍿', 7004, null),
  ('crackers', 'Snacks', 'cookie', null, 7005, null),
  ('breadsticks', 'Snacks', 'baguette', null, 7006, null),
  ('rice cakes', 'Snacks', 'cookie', null, 7007, null),
  ('chocolate', 'Snacks', 'juice', '🍫', 7008, null),
  ('sweets', 'Snacks', 'chocolate', '🍬', 7009, null),
  ('chewing gum', 'Snacks', 'chocolate', null, 7010, null),
  ('marshmallows', 'Snacks', 'chocolate', null, 7011, null),
  ('cereal bars', 'Snacks', 'cereal', null, 7012, null),
  ('dried fruit', 'Snacks', 'crisps', null, 7013, null),
  ('salsa', 'Snacks', 'jar', null, 7014, null),
  ('guacamole', 'Snacks', 'jar', null, 7015, null),
  ('hummus', 'Snacks', 'jar', null, 7016, null),
  ('salted peanuts', 'Snacks', 'nuts', '🥜', 7017, null),
  ('cheese puffs', 'Snacks', 'crisps', null, 7018, null),
  ('corn snacks', 'Snacks', 'crisps', null, 7019, null),
  ('dark chocolate', 'Snacks', 'chocolate', '🍫', 7020, null),
  ('milk chocolate', 'Snacks', 'chocolate', '🍫', 7021, null),
  ('white chocolate', 'Snacks', 'chocolate', '🍫', 7022, null),
  ('liquorice', 'Snacks', 'lolly', null, 7023, null),
  ('toffee', 'Snacks', 'lolly', '🍬', 7024, null),
  ('jelly sweets', 'Snacks', 'lolly', '🍬', 7025, null),
  ('protein bar', 'Snacks', 'bar', null, 7026, null),
  ('tzatziki', 'Snacks', 'jar', null, 7027, null),
  ('pickled onions', 'Snacks', 'jar', null, 7028, null),
  ('seaweed snacks', 'Snacks', 'bag', null, 7029, null),
  ('toilet paper', 'Household', 'toiletPaper', '🧻', 8000, 17),
  ('kitchen roll', 'Household', 'toiletPaper', '🧻', 8001, null),
  ('tissues', 'Household', 'toiletPaper', null, 8002, null),
  ('bin bags', 'Household', 'binBag', '🗑️', 8003, null),
  ('food bags', 'Household', 'binBag', null, 8004, null),
  ('freezer bags', 'Household', 'binBag', null, 8005, null),
  ('cling film', 'Household', 'foil', null, 8006, null),
  ('aluminium foil', 'Household', 'foil', null, 8007, null),
  ('baking paper', 'Household', 'foil', null, 8008, null),
  ('washing up liquid', 'Household', 'detergent', '🧽', 8009, 18),
  ('dishwasher tablets', 'Household', 'detergent', null, 8010, null),
  ('dish cloths', 'Household', 'sponge', null, 8011, null),
  ('sponges', 'Household', 'sponge', '🧽', 8012, null),
  ('scourers', 'Household', 'sponge', null, 8013, null),
  ('rubber gloves', 'Household', 'sponge', '🧤', 8014, null),
  ('laundry detergent', 'Household', 'detergent', '🧺', 8015, null),
  ('fabric softener', 'Household', 'detergent', null, 8016, null),
  ('stain remover', 'Household', 'detergent', null, 8017, null),
  ('surface cleaner', 'Household', 'spray', '🧴', 8018, null),
  ('bleach', 'Household', 'aerosol', null, 8019, null),
  ('toilet cleaner', 'Household', 'aerosol', null, 8020, null),
  ('oven cleaner', 'Household', 'aerosol', null, 8021, null),
  ('window cleaner', 'Household', 'spray', null, 8022, null),
  ('air freshener', 'Household', 'spray', null, 8023, null),
  ('insect spray', 'Household', 'spray', null, 8024, null),
  ('batteries', 'Household', 'battery', '🔋', 8025, null),
  ('light bulbs', 'Household', 'bulb', '💡', 8026, null),
  ('candles', 'Household', 'candle', '🕯️', 8027, null),
  ('matches', 'Household', 'candle', null, 8028, null),
  ('tape', 'Household', 'tube', null, 8029, null),
  ('dishwasher salt', 'Household', 'detergent', null, 8030, null),
  ('rinse aid', 'Household', 'detergent', null, 8031, null),
  ('drain cleaner', 'Household', 'spray', null, 8032, null),
  ('descaler', 'Household', 'spray', null, 8033, null),
  ('floor cleaner', 'Household', 'spray', null, 8034, null),
  ('furniture polish', 'Household', 'spray', null, 8035, null),
  ('microfibre cloths', 'Household', 'towel', null, 8036, null),
  ('napkins', 'Household', 'napkin', null, 8037, null),
  ('paper plates', 'Household', 'napkin', null, 8038, null),
  ('straws', 'Household', 'napkin', null, 8039, null),
  ('food containers', 'Household', 'bag', null, 8040, null),
  ('lighter', 'Household', 'candle', null, 8041, null),
  ('pet food', 'Household', 'can', null, 8042, null),
  ('plant food', 'Household', 'spray', null, 8043, null),
  ('flowers', 'Household', 'herbs', null, 8044, null),
  ('clothes pegs', 'Household', 'tape', null, 8045, null),
  ('shampoo', 'Personal care', 'shampoo', '🧴', 9000, null),
  ('conditioner', 'Personal care', 'shampoo', '🧴', 9001, null),
  ('shower gel', 'Personal care', 'soap', '🧴', 9002, null),
  ('soap', 'Personal care', 'soap', '🧼', 9003, null),
  ('hand soap', 'Personal care', 'soap', '🧼', 9004, null),
  ('hand sanitiser', 'Personal care', 'soap', null, 9005, null),
  ('hand cream', 'Personal care', 'soap', null, 9006, null),
  ('moisturiser', 'Personal care', 'soap', null, 9007, null),
  ('lip balm', 'Personal care', 'soap', null, 9008, null),
  ('sun cream', 'Personal care', 'soap', '🧴', 9009, null),
  ('deodorant', 'Personal care', 'deodorant', null, 9010, null),
  ('toothpaste', 'Personal care', 'toothpaste', '🪥', 9011, null),
  ('toothbrush', 'Personal care', 'toothbrush', '🪥', 9012, null),
  ('mouthwash', 'Personal care', 'toothpaste', null, 9013, null),
  ('dental floss', 'Personal care', 'toothpaste', null, 9014, null),
  ('razors', 'Personal care', 'toothbrush', '🪒', 9015, null),
  ('shaving foam', 'Personal care', null, null, 9016, null),
  ('hairbrush', 'Personal care', 'toothbrush', null, 9017, null),
  ('hair gel', 'Personal care', null, null, 9018, null),
  ('cotton buds', 'Personal care', 'sponge', null, 9019, null),
  ('cotton pads', 'Personal care', 'sponge', null, 9020, null),
  ('wet wipes', 'Personal care', 'sponge', null, 9021, null),
  ('nail clippers', 'Personal care', 'toothbrush', null, 9022, null),
  ('sanitary pads', 'Personal care', 'pills', null, 9023, null),
  ('tampons', 'Personal care', 'pills', null, 9024, null),
  ('plasters', 'Personal care', 'pills', '🩹', 9025, null),
  ('antiseptic cream', 'Personal care', 'pills', null, 9026, null),
  ('paracetamol', 'Personal care', 'pills', '💊', 9027, null),
  ('ibuprofen', 'Personal care', 'pills', '💊', 9028, null),
  ('throat lozenges', 'Personal care', 'pills', null, 9029, null),
  ('vitamins', 'Personal care', 'pills', '💊', 9030, null),
  ('face wash', 'Personal care', 'soap', null, 9031, null),
  ('face cream', 'Personal care', 'lotion', '🧴', 9032, null),
  ('micellar water', 'Personal care', 'lotion', '🧴', 9033, null),
  ('makeup remover', 'Personal care', 'lotion', null, 9034, null),
  ('aftershave', 'Personal care', 'deodorant', null, 9035, null),
  ('hairspray', 'Personal care', 'aerosol', null, 9036, null),
  ('dry shampoo', 'Personal care', 'aerosol', null, 9037, null),
  ('hair ties', 'Personal care', 'tape', null, 9038, null),
  ('cotton wool', 'Personal care', 'towel', null, 9039, null),
  ('nail file', 'Personal care', 'tape', null, 9040, null),
  ('tweezers', 'Personal care', 'tape', null, 9041, null),
  ('contact lens solution', 'Personal care', 'lotion', null, 9042, null),
  ('eye drops', 'Personal care', 'tube', null, 9043, null),
  ('allergy tablets', 'Personal care', 'pills', '💊', 9044, null),
  ('cough syrup', 'Personal care', 'tube', null, 9045, null),
  ('cold remedy', 'Personal care', 'pills', '💊', 9046, null),
  ('indigestion tablets', 'Personal care', 'pills', '💊', 9047, null),
  ('rehydration salts', 'Personal care', 'spice', null, 9048, null)
on conflict (lower(trim(name))) where household_id is null
do update set
  category = excluded.category,
  icon = excluded.icon,
  emoji = excluded.emoji,
  sort_order = excluded.sort_order,
  suggested_rank = excluded.suggested_rank;
