-- Round 12: repeating events.
--
-- §4.3: "Recurrence, simplified: repeats X times per week or month; ends after
-- X times. Deleting asks: this one, or all of them?" Marçal's version of the
-- same thing, after using the calendar for a fortnight: *"every sunday there's
-- gym for 10 times from x time to x time. then when editing one of this events
-- the system should ask the user if they want to update them all or just that
-- day."*
--
-- ## Four columns, no new table
--
-- The obvious shape for recurrence is a rule stored once and expanded on the
-- fly — one row saying "every Sunday, ten times", and a calendar that works out
-- the ten days whenever it draws. It is how Google does it, and it is why
-- Google's API has recurringEventId, instance ids, and a vocabulary for "this
-- occurrence is an exception".
--
-- Niu writes the ten rows instead. Each occurrence is an ordinary event that
-- happens to carry a series id, which means **everything already built keeps
-- working with no changes at all**: the month grid draws them, the day list
-- sorts them, RLS protects them, attendees and confirmations attach to them,
-- and the Google push sends ten ordinary events whose ids come from their own
-- uuids. No RRULE on either side, and no exception machinery — because an
-- occurrence you edited on its own is not an exception here, it is just a row
-- with different values in it.
--
-- The price is that a series is finite. "Every Sunday forever" cannot be
-- written down, and the app caps a series at 60 occurrences (MAX_OCCURRENCES in
-- src/lib/recurrence.ts). §4.3 asked for the finite version, so this is the
-- shape of the feature rather than a corner cut around it.
--
-- ## No new policies, and why that is not an oversight
--
-- CLAUDE.md's first hard rule is that a new table means a new RLS policy in the
-- same commit. There is no new table: these are four columns on `events`, which
-- has had its four policies since 0012 and enforces them on every row whatever
-- is written in these columns. A series is not a new kind of thing to protect —
-- it is ten of the thing that was already protected.
--
-- Run it once in the Supabase dashboard under SQL Editor. Safe to re-run.

alter table public.events
  -- Null for a one-off, which is most events. Every occurrence of one series
  -- carries the same value. Generated by the app rather than the database: the
  -- ten rows are written in one insert and they all need to know it up front.
  add column if not exists series_id uuid,

  -- Where in the series this occurrence is, from 0 — what "3 of 10" counts.
  add column if not exists series_index integer not null default 0,

  -- How many were written. Deliberately *not* recomputed when one is removed:
  -- deleting the fourth gym session should not renumber the other nine, and
  -- "3 of 10" is a fact about the series you asked for.
  add column if not exists series_count integer not null default 1,

  -- How often it comes round. The same four words the app uses; kept as text
  -- rather than an enum so adding a fifth is an app change and not a migration
  -- that has to run before either phone can be updated.
  add column if not exists series_rule text;

-- The three shapes worth refusing. A count below the index would make "3 of 1";
-- a rule on a one-off row would make a series of one; and a series id with no
-- rule beside it is a series that cannot say what it is.
alter table public.events
  drop constraint if exists events_series_rule_known;
alter table public.events
  add constraint events_series_rule_known
  check (series_rule is null or series_rule in ('daily', 'weekly', 'fortnightly', 'monthly'));

alter table public.events
  drop constraint if exists events_series_shape;
alter table public.events
  add constraint events_series_shape
  check (
    series_index >= 0
    and series_count >= 1
    and series_index < series_count
    and (series_id is null) = (series_rule is null)
  );

-- Every question asked of a series is "all the rows with this id", and the
-- household is in front because that is what RLS filters on first. Partial,
-- because the overwhelming majority of events are one-offs and there is no
-- reason to carry them in this index.
create index if not exists events_series_idx
  on public.events (household_id, series_id, series_index)
  where series_id is not null;
